#ifndef GAMELOG_INCLUDE_H
#define GAMELOG_INCLUDE_H
#include <boost/log/core.hpp>  
#include <boost/log/trivial.hpp>  
#include <boost/log/sinks.hpp>  
#include <boost/log/attributes.hpp>  
#include <boost/log/common.hpp>  
#include <boost/log/expressions.hpp>
#include <boost/log/exceptions.hpp>
#include <boost/log/sources/logger.hpp>
#include <boost/log/utility/record_ordering.hpp>
#include <boost/log/sinks/async_frontend.hpp>
#include <boost/log/utility/setup/file.hpp>
#include <boost/log/utility/setup/file.hpp>
#include <boost/log/utility/setup/console.hpp>
#include <boost/log/utility/setup/common_attributes.hpp>
#include <boost/log/attributes/timer.hpp>
#include <boost/log/attributes/named_scope.hpp>
#include <boost/log/sources/logger.hpp>
#include <boost/log/support/date_time.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/thread/thread.hpp>
#endif